FROM python:2.7

MAINTAINER Chris Henry <henry.christopher@gmail.com>

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --force-yes libmysqlclient-dev

RUN pip install --upgrade pip

COPY data-imports/requirements.txt /root/requirements.txt
RUN pip --no-cache-dir install -r /root/requirements.txt

COPY luigi/luigi.cfg /root/luigi.cfg

ENV PYTHONPATH="/root/data-imports"
CMD ["luigi", "--scheduler-host", "luigid", "--no-lock", "--module", "luigi_master", "ImportAll"]
