FROM python:2.7

MAINTAINER Chris Henry <henry.christopher@gmail.com>

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY luigi/requirements.txt /root/requirements.txt
RUN pip --no-cache-dir install -r /root/requirements.txt

CMD ["luigid", "--logdir", "/root/logs", "--state-path", "/root/state/luigi-state.pkl", "--port", "8082"]
