version: '2'
services:

  db:
    build:
      dockerfile: Dockerfile.mysql
      context: .
    env_file: .env
    volumes:
      - ./mysql-data/:/var/lib/mysql/

  db-provision:
    build:
      dockerfile: Dockerfile.mysql-provision
      context: .
    environment:
      MYSQL_HOST: db
    env_file: .env
    depends_on:
      - db

  postgres:
    image: postgres:9.6
    volumes:
      - ./nyc-db:/root/
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  postgrest:
    image: begriffs/postgrest
    volumes:
      - ./log/api:/var/log:rw
    env_file: .env
    ports:
      - "3000:3000"
    # volumes:
    #   - ./postgrest.conf:/etc/postgrest.conf
    environment:
      POSTGREST_ANONYMOUS:      'anonymous'
      PGRST_MAX_ROWS:           '200'
      PG_ENV_POSTGRES_USER:     'deltanyc'
      PG_ENV_POSTGRES_DB:       'deltanyc_rails'
      PG_ENV_POSTGRES_PASSWORD: 'password'
      PG_PORT_5432_TCP_ADDR:    'postgres'
      PG_PORT_5432_TCP_PORT:    '5432'
      POSTGREST_MAX_ROWS:       '1000000'
      POSTGREST_POOL:           '200'
    links:
      - postgres
    depends_on:
      - postgres
    command: "postgrest postgres://deltanyc:password@postgres:5432/deltanyc_rails --port 3000 --schema public -a anonymous -m 200"
  web:
    build:
      context: ./angular-rails-app/
    command: ["sh", "-c", "/angular-rails-app/docker-cmd.sh"]
    env_file: .env
    environment:
      MYSQL_HOST: db
      POSTGRES_HOST: postgres
    volumes:
      - ./angular-rails-app/:/angular-rails-app/
    ports:
      - "80:80"
    depends_on:
      - db
      - postgres

  nb:
    build:
      context: .
      dockerfile: Dockerfile.nb
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    environment:
      MYSQL_HOST: db
    volumes:
      - ./JPF/:/root/JPF/
      - ./data-imports/:/root/data-imports/
      - ./data/:/root/heatseek/
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db

  luigid:
    build:
      context: .
      dockerfile: Dockerfile.luigid
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    ports:
      - "8082:8082"  # default luigid port
    volumes:
      - ./luigi:/root/
    # Link to db for task history
    depends_on:
      - db
    links:
      - db

  luigi-import-worker:
    build:
      context: .
      dockerfile: Dockerfile.luigi-import-worker
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    environment:
      MYSQL_HOST: db
    volumes:
      - ./data-imports/:/root/data-imports/
      - ./data/:/root/heatseek/
    depends_on:
      - db
      - luigid
    links:
      - db
      - luigid
