version: '2'
services:
  db:
    build:
      dockerfile: Dockerfile.mysql
      context: .
    env_file: .env
    volumes:
      - ./mysql-data/:/var/lib/mysql/
  db-udf:
    build:
      dockerfile: Dockerfile.mysql-udf
      context: .
    environment:
      MYSQL_HOST: db
    env_file: .env
    depends_on:
      - db
  web:
    build:
      context: ./angular-rails-app/
    command: ["sh", "-c", "/angular-rails-app/docker-cmd.sh"]
    env_file: .env
    environment:
      MYSQL_HOST: db
    volumes:
      - ./angular-rails-app/:/angular-rails-app/
    ports:
      - "80:80"
    depends_on:
      - db
  nb:
    build:
      context: .
      dockerfile: Dockerfile.nb
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    environment:
      MYSQL_HOST: db
    volumes:
      - ./JPF/:/root/JPF/
      - ./data-imports/:/root/data-imports/
      - ./data/:/root/heatseek/
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db
  luigid:
    build:
      context: .
      dockerfile: Dockerfile.luigid
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    ports:
      - "8082:8082"  # default luigid port
    volumes:
      - ./luigi:/root/
    # Link to db for task history
    depends_on:
      - db
    links:
      - db
  luigi-import-worker:
    build:
      context: .
      dockerfile: Dockerfile.luigi-import-worker
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    environment:
      MYSQL_HOST: db
    volumes:
      - ./data-imports/:/root/data-imports/
      - ./data/:/root/heatseek/
    depends_on:
      - db
      - luigid
    links:
      - db
      - luigid
